### ISSUE TITLE
查找子字符串问题

### ISSUE THREAD

**Issue by vFabric** [qinjx/30min_guides#11]
查找子字符串

string="alibaba is a great company"
echo `expr index "$string" is`#输出：8，这个语句的意思是：找出单词is在这名话中的位置

试了下, 输出好像跟描述的不符.
"expr index strings chars，只要chars中的任意一个字符在strings中出现，就返回所在的位置，否则返回0"
是这个意思吗?

**Comment by qinjx** [comment]
你是对的，实际输出是3，找到字母i就可以了
